name: Lighthouse
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lighthouse-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm install
      - run: npm run build

      - name: Lighthouse report
        uses: treosh/lighthouse-ci-action@12.1.0
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: "./lighthouse.config.js"
          temporaryPublicStorage: true
